name = "Timestamp64"
uuid = "bb4eac3f-01a0-4c2b-bd7e-ee6d71616039"
authors = ["Rino Beeli <40661605+rbeeli@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
